name: ai-notes-api-deploy
description: Build and deploy to Cloud Run service ai-notes-api on push to "^main$"
filename: cloudbuild/api.yaml
github:
  name: ai-notes
  owner: <GITHUB_OWNER>
  push:
    branch: ^main$
serviceAccount: projects/ai-notes-507510/serviceAccounts/sa-ai-notes-build@ai-notes-507510.iam.gserviceaccount.com
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - ai-notes-api
substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed
  _SERVICE_NAME: ai-notes-api
