name: ai-notes-web-deploy
description: Build and deploy to Cloud Run service ai-notes-web on push to "^main$"
filename: cloudbuild/web.yaml
github:
  name: ai-notes
  owner: <GITHUB_OWNER>
  push:
    branch: ^main$
serviceAccount: projects/ai-notes-507510/serviceAccounts/sa-ai-notes-build@ai-notes-507510.iam.gserviceaccount.com
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - ai-notes-web
substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _DEPLOY_REGION: europe-west1
  _PLATFORM: managed
  _SERVICE_NAME: ai-notes-web
  _VITE_FIREBASE_API_KEY: <FIREBASE_API_KEY>
  _VITE_FIREBASE_AUTH_DOMAIN: ai-notes-507510.firebaseapp.com
  _VITE_FIREBASE_PROJECT_ID: ai-notes-507510
  _VITE_FIREBASE_STORAGE_BUCKET: ai-notes-507510.firebasestorage.app
  _VITE_FIREBASE_MESSAGING_SENDER_ID: '786405456691'
  _VITE_FIREBASE_APP_ID: 1:786405456691:web:11c00589c1b217981e1c46
  _VITE_FIREBASE_MEASUREMENT_ID: G-VRBFCMKKJ1
